---
- name: Update /etc/sftpgo/sftpgo.json
  template:
    src: "{{ item }}"
    dest: "/etc/sftpgo/sftpgo.json"
    backup: yes
    owner: sftpgo
    group: sftpgo
    mode: 0640
  register: __sftpgo_json
  with_first_found:
    - templates/{{ inventory_hostname }}/sftpgo.json.j2
    - templates/sftpgo/sftpgo.json.j2
    - sftpgo.json.j2
  notify: Restart sftpgo        # restart needed (reload does not seem to get changes)

- name: Update /etc/sftpgo/sftpgo.env
  template:
    src: "{{ item }}"
    dest: "/etc/sftpgo/sftpgo.env"
    backup: yes
    owner: sftpgo
    group: sftpgo
    mode: 0640
  register: __sftpgo_env
  with_first_found:
    - templates/{{ inventory_hostname }}/sftpgo.env.j2
    - templates/sftpgo/sftpgo.env.j2
    - sftpgo.env.j2
  notify: Restart sftpgo        # restart needed (reload does not seem to get changes)

# Restart sftpgo always when api or config file changes
- name: Restart sftpgo service
  systemd:
    name: sftpgo
    state: restarted
  when: __sftpgo_env.changed or __sftpgo_json.changed

