---
# tasks file for ansible-sftpgo role


## Install sftpgo
- import_tasks: "install.yml"
  tags:
    - "sftpgo-install"

## Configure sftpgo
- import_tasks: "configure.yml"
  tags:
    - "sftpgo-config"

## Add optional S3 virtual folders before assigning them to users
- import_tasks: "s3_virtual_folders.yml"
  when:
    - sftpgo_s3_virtual_folders | length > 0
  tags:
    - "sftpgo-s3-virtual-folders"
    - "sftpgo-users"

## Add sftpgo users
- import_tasks: "users.yml"
  tags:
    - "sftpgo-users"

## Add bindfs mount points
- import_tasks: "bindfs.yml"
  when:
    - sftpgo_bindfs_mounts is defined
  tags:
    - "sftpgo-bindfs"
